### ISSUE TITLE
Create Pub/Sub Alert Channel in Lacework via Terraform

### ISSUE THREAD

**Issue by afiune** [mikelaramie/lacework-snippets#1]
It is possible to create the pub/sub alert channel in Lacework via Terraform,
it would be cool if we could add that to https://github.com/mikelaramie/lacework-snippets/tree/main/pubsub-to-gcs

Docs: https://support.lacework.com/hc/en-us/articles/360047496514-Google-Cloud-Pub-Sub#create-a-lacework-gcp-pubsub-alert-channel-using-terraform

**Comment by mikelaramie** [comment]
Hey Salim!  The code actually does use the 'lacework_alert_channel_gcp_pub_sub' resource to [create the pub/sub alert channel](https://github.com/mikelaramie/lacework-snippets/blob/0a377b80c572d26c270b412cd193987295106b05/gcp/pubsub-to-gcs/main.tf#L28) - such a huge help!  Or did I misunderstand your request?

The readme was listing out the steps to perform everything manually; I've updated it a bit to make it clearer that the code in the repo automates everything but the service account creation.

**Comment by afiune** [comment]
You did not misunderstand my question, I am just blind 😂 - Disregard! You are too awesome man. Closing......

![tenor-159404684](https://user-images.githubusercontent.com/5712253/124621620-a81d6b80-de37-11eb-9e6e-d28b3b70909e.gif)
